name: Deploy to Private Server

on:
  push:
    branches:
      - master # Lub 'main', jeśli twoja domyślna gałąź to main

jobs:
  deploy:
    # Uruchomimy to lokalnie na komputerze używając nasłuchiwacza 'self-hosted'
    runs-on: self-hosted

    steps:
      - name: Pobieranie najnowszego kodu bota
        uses: actions/checkout@v4

      - name: Ustawianie środowiska Node.js (v20)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalacja potrzebnych paczek
        run: npm ci

      - name: Budowanie bota (Kompilacja TypeScript)
        run: npm run build

      - name: Generowanie klienta Prisma ORM
        run: npx prisma generate

      - name: Odtwarzanie bazy danych i podnoszenie Bota (PM2)
        run: |
          npx prisma db push --accept-data-loss
          pm2 start ecosystem.config.js || pm2 restart ecosystem.config.js
          pm2 save
